spring:
  application:
    name: techefx-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tijdrame/techefxRepo.git 
          default-label: main
        
server:
  port: ${port:8888}
